import json
import os

us_it_companies = [
    {
        "name": "Apple",
        "legal_name": "Apple Inc.",
        "ticker": "AAPL",
        "category": "Information Technology",
        "subcategory": "Consumer Electronics & Software",
        "careers_url": "https://www.apple.com/careers/us/",
        "ats": "Proprietary",
        "city": "Cupertino",
        "state": "CA",
        "country": "US",
        "description": "Designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories.",
        "employees": "161000"
    },
    {
        "name": "Microsoft",
        "legal_name": "Microsoft Corporation",
        "ticker": "MSFT",
        "category": "Information Technology",
        "subcategory": "Enterprise Software & Cloud",
        "careers_url": "https://careers.microsoft.com/",
        "ats": "iCIMS",
        "city": "Redmond",
        "state": "WA",
        "country": "US",
        "description": "Develops, licenses, and supports software, services, devices, and solutions worldwide.",
        "employees": "221000"
    },
    {
        "name": "Alphabet (Google)",
        "legal_name": "Alphabet Inc.",
        "ticker": "GOOGL",
        "category": "Information Technology",
        "subcategory": "Internet Services & AI",
        "careers_url": "https://careers.google.com/",
        "ats": "Proprietary",
        "city": "Mountain View",
        "state": "CA",
        "country": "US",
        "description": "Provides various products and platforms globally, including Google Search, Ads, Cloud, and YouTube.",
        "employees": "182000"
    },
    {
        "name": "Amazon",
        "legal_name": "Amazon.com, Inc.",
        "ticker": "AMZN",
        "category": "Information Technology",
        "subcategory": "E-Commerce & Cloud Computing",
        "careers_url": "https://www.amazon.jobs/",
        "ats": "Proprietary",
        "city": "Seattle",
        "state": "WA",
        "country": "US",
        "description": "Engages in the retail sale of consumer products and subscriptions, and offers AWS cloud services.",
        "employees": "1525000"
    },
    {
        "name": "Meta (Facebook)",
        "legal_name": "Meta Platforms, Inc.",
        "ticker": "META",
        "category": "Information Technology",
        "subcategory": "Social Media & Metaverse",
        "careers_url": "https://www.metacareers.com/",
        "ats": "Proprietary",
        "city": "Menlo Park",
        "state": "CA",
        "country": "US",
        "description": "Develops products that enable people to connect and share with friends and family through mobile devices, PCs, and VR/AR headsets.",
        "employees": "67000"
    },
    {
        "name": "NVIDIA",
        "legal_name": "NVIDIA Corporation",
        "ticker": "NVDA",
        "category": "Information Technology",
        "subcategory": "Semiconductors & AI Computing",
        "careers_url": "https://www.nvidia.com/en-us/about-nvidia/careers/",
        "ats": "Workday",
        "city": "Santa Clara",
        "state": "CA",
        "country": "US",
        "description": "Provides graphics, and compute and networking solutions in the United States, Taiwan, China, and internationally.",
        "employees": "29000"
    },
    {
        "name": "Tesla",
        "legal_name": "Tesla, Inc.",
        "ticker": "TSLA",
        "category": "Information Technology",
        "subcategory": "Electric Vehicles & Clean Energy",
        "careers_url": "https://www.tesla.com/careers",
        "ats": "Proprietary",
        "city": "Austin",
        "state": "TX",
        "country": "US",
        "description": "Designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems.",
        "employees": "140000"
    },
    {
        "name": "Netflix",
        "legal_name": "Netflix, Inc.",
        "ticker": "NFLX",
        "category": "Information Technology",
        "subcategory": "Streaming & Entertainment Tech",
        "careers_url": "https://jobs.netflix.com/",
        "ats": "Workday",
        "city": "Los Gatos",
        "state": "CA",
        "country": "US",
        "description": "Provides entertainment services, offering TV series, documentaries, feature films, and mobile games.",
        "employees": "13000"
    },
    {
        "name": "Salesforce",
        "legal_name": "Salesforce, Inc.",
        "ticker": "CRM",
        "category": "Information Technology",
        "subcategory": "Enterprise CRM & SaaS",
        "careers_url": "https://careers.salesforce.com/",
        "ats": "Workday",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Provides customer relationship management technology that brings companies and customers together worldwide.",
        "employees": "72000"
    },
    {
        "name": "Adobe",
        "legal_name": "Adobe Inc.",
        "ticker": "ADBE",
        "category": "Information Technology",
        "subcategory": "Creative Software & Digital Experiences",
        "careers_url": "https://careers.adobe.com/us/en",
        "ats": "Workday",
        "city": "San Jose",
        "state": "CA",
        "country": "US",
        "description": "Operates as a diversified software company worldwide, offering Digital Media, Digital Experience, and Publishing.",
        "employees": "29000"
    },
    {
        "name": "Oracle",
        "legal_name": "Oracle Corporation",
        "ticker": "ORCL",
        "category": "Information Technology",
        "subcategory": "Database & Cloud Infrastructure",
        "careers_url": "https://careers.oracle.com/",
        "ats": "Oracle HCM",
        "city": "Austin",
        "state": "TX",
        "country": "US",
        "description": "Provides products and services that address enterprise information technology environments worldwide.",
        "employees": "164000"
    },
    {
        "name": "Cisco",
        "legal_name": "Cisco Systems, Inc.",
        "ticker": "CSCO",
        "category": "Information Technology",
        "subcategory": "Networking & Cybersecurity",
        "careers_url": "https://jobs.cisco.com/",
        "ats": "Avature",
        "city": "San Jose",
        "state": "CA",
        "country": "US",
        "description": "Designs and sells a broad range of technologies that power the Internet.",
        "employees": "84000"
    },
    {
        "name": "IBM",
        "legal_name": "International Business Machines Corporation",
        "ticker": "IBM",
        "category": "Information Technology",
        "subcategory": "IT Services, Cloud & Hybrid AI",
        "careers_url": "https://www.ibm.com/careers/",
        "ats": "BrassRing",
        "city": "Armonk",
        "state": "NY",
        "country": "US",
        "description": "Provides global hybrid cloud and AI, and consulting expertise.",
        "employees": "282000"
    },
    {
        "name": "Intel",
        "legal_name": "Intel Corporation",
        "ticker": "INTC",
        "category": "Information Technology",
        "subcategory": "Semiconductors",
        "careers_url": "https://jobs.intel.com/",
        "ats": "Workday",
        "city": "Santa Clara",
        "state": "CA",
        "country": "US",
        "description": "Designs, manufactures, and sells essential technologies for the cloud, smart, and connected devices.",
        "employees": "124000"
    },
    {
        "name": "AMD",
        "legal_name": "Advanced Micro Devices, Inc.",
        "ticker": "AMD",
        "category": "Information Technology",
        "subcategory": "Semiconductors",
        "careers_url": "https://careers.amd.com/careers-home",
        "ats": "SuccessFactors",
        "city": "Santa Clara",
        "state": "CA",
        "country": "US",
        "description": "Operates as a semiconductor company worldwide, offering processors, chipsets, GPUs, and adaptive SoCs.",
        "employees": "26000"
    },
    {
        "name": "Qualcomm",
        "legal_name": "Qualcomm Incorporated",
        "ticker": "QCOM",
        "category": "Information Technology",
        "subcategory": "Semiconductors & Wireless Tech",
        "careers_url": "https://careers.qualcomm.com/",
        "ats": "Workday",
        "city": "San Diego",
        "state": "CA",
        "country": "US",
        "description": "Engages in the development and commercialization of foundational technologies for the wireless industry.",
        "employees": "50000"
    },
    {
        "name": "ServiceNow",
        "legal_name": "ServiceNow, Inc.",
        "ticker": "NOW",
        "category": "Information Technology",
        "subcategory": "ITSM & Enterprise SaaS",
        "careers_url": "https://careers.servicenow.com/",
        "ats": "SmartRecruiters",
        "city": "Santa Clara",
        "state": "CA",
        "country": "US",
        "description": "Provides enterprise cloud computing solutions that define, structure, manage, and automate services.",
        "employees": "22000"
    },
    {
        "name": "Intuit",
        "legal_name": "Intuit Inc.",
        "ticker": "INTU",
        "category": "Information Technology",
        "subcategory": "Financial Software",
        "careers_url": "https://jobs.intuit.com/",
        "ats": "iCIMS",
        "city": "Mountain View",
        "state": "CA",
        "country": "US",
        "description": "Provides financial management and compliance products and services for consumers, small businesses, self-employed, and accounting professionals.",
        "employees": "18000"
    },
    {
        "name": "Uber",
        "legal_name": "Uber Technologies, Inc.",
        "ticker": "UBER",
        "category": "Information Technology",
        "subcategory": "Ride-Hailing & Logistics Tech",
        "careers_url": "https://www.uber.com/us/en/careers/",
        "ats": "iCIMS",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Develops and operates proprietary technology applications in the United States, Canada, and internationally.",
        "employees": "32000"
    },
    {
        "name": "Airbnb",
        "legal_name": "Airbnb, Inc.",
        "ticker": "ABNB",
        "category": "Information Technology",
        "subcategory": "Travel Marketplace Tech",
        "careers_url": "https://careers.airbnb.com/",
        "ats": "Greenhouse",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Operates a platform that enables hosts to offer stays and experiences to guests worldwide.",
        "employees": "6800"
    },
    {
        "name": "Stripe",
        "legal_name": "Stripe, Inc.",
        "ticker": "Private",
        "category": "Information Technology",
        "subcategory": "Fintech & Payments Infrastructure",
        "careers_url": "https://stripe.com/jobs",
        "ats": "Greenhouse",
        "city": "South San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Offers economic infrastructure for the internet, providing payment processing software and APIs for e-commerce websites and mobile applications.",
        "employees": "7000"
    },
    {
        "name": "SpaceX",
        "legal_name": "Space Exploration Technologies Corp.",
        "ticker": "Private",
        "category": "Information Technology",
        "subcategory": "Aerospace & Satellite Connectivity",
        "careers_url": "https://www.spacex.com/careers/",
        "ats": "Greenhouse",
        "city": "Hawthorne",
        "state": "CA",
        "country": "US",
        "description": "Designs, manufactures and launches advanced rockets and spacecraft; operates Starlink.",
        "employees": "13000"
    },
    {
        "name": "Palantir",
        "legal_name": "Palantir Technologies Inc.",
        "ticker": "PLTR",
        "category": "Information Technology",
        "subcategory": "Data Analytics & AI Defense",
        "careers_url": "https://www.palantir.com/careers/",
        "ats": "Lever",
        "city": "Denver",
        "state": "CO",
        "country": "US",
        "description": "Builds software that empowers organizations to effectively integrate their data, decisions, and operations.",
        "employees": "3800"
    },
    {
        "name": "Snowflake",
        "legal_name": "Snowflake Inc.",
        "ticker": "SNOW",
        "category": "Information Technology",
        "subcategory": "Cloud Data Warehousing",
        "careers_url": "https://careers.snowflake.com/us/en",
        "ats": "Greenhouse",
        "city": "Bozeman",
        "state": "MT",
        "country": "US",
        "description": "Provides a cloud-based data platform for data storage, computing, and analytics.",
        "employees": "7000"
    },
    {
        "name": "Databricks",
        "legal_name": "Databricks, Inc.",
        "ticker": "Private",
        "category": "Information Technology",
        "subcategory": "Data & AI Platform",
        "careers_url": "https://www.databricks.com/company/careers",
        "ats": "Greenhouse",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Unified data analytics platform for massive scale data engineering and data science.",
        "employees": "6000"
    },
    {
        "name": "Workday",
        "legal_name": "Workday, Inc.",
        "ticker": "WDAY",
        "category": "Information Technology",
        "subcategory": "HR & Financial SaaS",
        "careers_url": "https://workday.wd5.myworkdayjobs.com/Workday",
        "ats": "Workday",
        "city": "Pleasanton",
        "state": "CA",
        "country": "US",
        "description": "Provides enterprise cloud applications for finance and human resources.",
        "employees": "18000"
    },
    {
        "name": "Atlassian",
        "legal_name": "Atlassian Corporation",
        "ticker": "TEAM",
        "category": "Information Technology",
        "subcategory": "Collaboration Software",
        "careers_url": "https://www.atlassian.com/company/careers",
        "ats": "Lever",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Designs, develops, licenses, and maintains software for tracking software bugs and project management.",
        "employees": "11000"
    },
    {
        "name": "Zoom",
        "legal_name": "Zoom Video Communications, Inc.",
        "ticker": "ZM",
        "category": "Information Technology",
        "subcategory": "Video Communications",
        "careers_url": "https://careers.zoom.us/",
        "ats": "Workday",
        "city": "San Jose",
        "state": "CA",
        "country": "US",
        "description": "Provides a unified communications and collaboration platform.",
        "employees": "8400"
    },
    {
        "name": "Square (Block)",
        "legal_name": "Block, Inc.",
        "ticker": "SQ",
        "category": "Information Technology",
        "subcategory": "Fintech & Payments",
        "careers_url": "https://careers.squareup.com/",
        "ats": "SmartRecruiters",
        "city": "Oakland",
        "state": "CA",
        "country": "US",
        "description": "Creates tools that enable anyone to participate in the economy.",
        "employees": "12000"
    },
    {
        "name": "Palo Alto Networks",
        "legal_name": "Palo Alto Networks, Inc.",
        "ticker": "PANW",
        "category": "Information Technology",
        "subcategory": "Cybersecurity",
        "careers_url": "https://jobs.paloaltonetworks.com/",
        "ats": "SmartRecruiters",
        "city": "Santa Clara",
        "state": "CA",
        "country": "US",
        "description": "Provides cybersecurity solutions worldwide.",
        "employees": "13000"
    },
    {
        "name": "CrowdStrike",
        "legal_name": "CrowdStrike Holdings, Inc.",
        "ticker": "CRWD",
        "category": "Information Technology",
        "subcategory": "Cybersecurity",
        "careers_url": "https://www.crowdstrike.com/careers/",
        "ats": "Workday",
        "city": "Austin",
        "state": "TX",
        "country": "US",
        "description": "Provides cloud-delivered protection of endpoints, cloud workloads, identity and data.",
        "employees": "7000"
    },
    {
        "name": "Cloudflare",
        "legal_name": "Cloudflare, Inc.",
        "ticker": "NET",
        "category": "Information Technology",
        "subcategory": "Web Infrastructure & Security",
        "careers_url": "https://www.cloudflare.com/careers/",
        "ats": "Greenhouse",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Operates a cloud platform that delivers a range of network services to businesses worldwide.",
        "employees": "3600"
    },
    {
        "name": "Splunk (Cisco)",
        "legal_name": "Splunk Inc.",
        "ticker": "Acquired",
        "category": "Information Technology",
        "subcategory": "Data Analytics",
        "careers_url": "https://www.splunk.com/en_us/careers.html",
        "ats": "Avature",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Provides software and cloud solutions that deliver and operationalize insights from the data generated by digital systems.",
        "employees": "8000"
    },
    {
        "name": "DocuSign",
        "legal_name": "DocuSign, Inc.",
        "ticker": "DOCU",
        "category": "Information Technology",
        "subcategory": "E-Signature & Contract Management",
        "careers_url": "https://careers.docusign.com/",
        "ats": "Greenhouse",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Provides electronic signature solution worldwide.",
        "employees": "7300"
    },
    {
        "name": "Twilio",
        "legal_name": "Twilio Inc.",
        "ticker": "TWLO",
        "category": "Information Technology",
        "subcategory": "Cloud Communications Platform",
        "careers_url": "https://www.twilio.com/company/jobs",
        "ats": "Greenhouse",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Provides a cloud communications platform that enables developers to build, scale, and operate communications within software applications.",
        "employees": "6400"
    },
    {
        "name": "MongoDB",
        "legal_name": "MongoDB, Inc.",
        "ticker": "MDB",
        "category": "Information Technology",
        "subcategory": "Database Platform",
        "careers_url": "https://www.mongodb.com/careers",
        "ats": "Greenhouse",
        "city": "New York",
        "state": "NY",
        "country": "US",
        "description": "Provides a general-purpose database platform worldwide.",
        "employees": "4800"
    },
    {
        "name": "HubSpot",
        "legal_name": "HubSpot, Inc.",
        "ticker": "HUBS",
        "category": "Information Technology",
        "subcategory": "Marketing & CRM SaaS",
        "careers_url": "https://www.hubspot.com/careers",
        "ats": "Greenhouse",
        "city": "Cambridge",
        "state": "MA",
        "country": "US",
        "description": "Provides a cloud-based customer relationship management (CRM) platform.",
        "employees": "7600"
    },
    {
        "name": "Coinbase",
        "legal_name": "Coinbase Global, Inc.",
        "ticker": "COIN",
        "category": "Information Technology",
        "subcategory": "Cryptocurrency Platform",
        "careers_url": "https://www.coinbase.com/careers",
        "ats": "Greenhouse",
        "city": "Remote",
        "state": "US",
        "country": "US",
        "description": "Provides financial infrastructure and technology for the cryptoeconomy.",
        "employees": "3400"
    },
    {
        "name": "Electronic Arts",
        "legal_name": "Electronic Arts Inc.",
        "ticker": "EA",
        "category": "Information Technology",
        "subcategory": "Video Games",
        "careers_url": "https://ea.gr8people.com/",
        "ats": "Gr8 People",
        "city": "Redwood City",
        "state": "CA",
        "country": "US",
        "description": "Develops, markets, publishes, and distributes games, content, and services.",
        "employees": "13400"
    },
    {
        "name": "Epic Games",
        "legal_name": "Epic Games, Inc.",
        "ticker": "Private",
        "category": "Information Technology",
        "subcategory": "Video Games & Game Engines",
        "careers_url": "https://www.epicgames.com/site/en-US/careers",
        "ats": "Workday",
        "city": "Cary",
        "state": "NC",
        "country": "US",
        "description": "Develops the Unreal Engine and popular games such as Fortnite.",
        "employees": "4000"
    },
    {
        "name": "OpenAI",
        "legal_name": "OpenAI, L.L.C.",
        "ticker": "Private",
        "category": "Information Technology",
        "subcategory": "Artificial Intelligence Research",
        "careers_url": "https://openai.com/careers",
        "ats": "Greenhouse",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "AI research and deployment company behind ChatGPT and DALL-E.",
        "employees": "1500"
    },
    {
        "name": "Anthropic",
        "legal_name": "Anthropic PBC",
        "ticker": "Private",
        "category": "Information Technology",
        "subcategory": "Artificial Intelligence Research",
        "careers_url": "https://www.anthropic.com/careers",
        "ats": "Lever",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "An AI safety and research company, creators of Claude.",
        "employees": "300"
    },
    {
        "name": "Discord",
        "legal_name": "Discord Inc.",
        "ticker": "Private",
        "category": "Information Technology",
        "subcategory": "Communication Platform",
        "careers_url": "https://discord.com/jobs",
        "ats": "Greenhouse",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Voice, video, and text communication service used by gamers and communities.",
        "employees": "900"
    },
    {
        "name": "Roblox",
        "legal_name": "Roblox Corporation",
        "ticker": "RBLX",
        "category": "Information Technology",
        "subcategory": "Gaming Platform",
        "careers_url": "https://careers.roblox.com/",
        "ats": "Greenhouse",
        "city": "San Mateo",
        "state": "CA",
        "country": "US",
        "description": "Operates a free-to-play immersive entertainment platform.",
        "employees": "2400"
    },
    {
        "name": "Snap",
        "legal_name": "Snap Inc.",
        "ticker": "SNAP",
        "category": "Information Technology",
        "subcategory": "Social Media & AR",
        "careers_url": "https://careers.snap.com/",
        "ats": "Workday",
        "city": "Santa Monica",
        "state": "CA",
        "country": "US",
        "description": "Operates as a technology company, creating Snapchat and AR products.",
        "employees": "5200"
    },
    {
        "name": "Pinterest",
        "legal_name": "Pinterest, Inc.",
        "ticker": "PINS",
        "category": "Information Technology",
        "subcategory": "Social Media",
        "careers_url": "https://www.pinterestcareers.com/",
        "ats": "Workday",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Operates a visual discovery engine.",
        "employees": "3900"
    },
    {
        "name": "Dropbox",
        "legal_name": "Dropbox, Inc.",
        "ticker": "DBX",
        "category": "Information Technology",
        "subcategory": "Cloud Storage & Collaboration",
        "careers_url": "https://jobs.dropbox.com/",
        "ats": "Greenhouse",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Provides a collaboration platform worldwide.",
        "employees": "3100"
    },
    {
        "name": "Figma",
        "legal_name": "Figma, Inc.",
        "ticker": "Private",
        "category": "Information Technology",
        "subcategory": "Design Software",
        "careers_url": "https://www.figma.com/careers/",
        "ats": "Greenhouse",
        "city": "San Francisco",
        "state": "CA",
        "country": "US",
        "description": "Collaborative web application for interface design.",
        "employees": "1200"
    },
    {
        "name": "Canva",
        "legal_name": "Canva US (Canva Pty Ltd)",
        "ticker": "Private",
        "category": "Information Technology",
        "subcategory": "Design Software",
        "careers_url": "https://www.canva.com/careers/",
        "ats": "Lever",
        "city": "Austin",
        "state": "TX",
        "country": "US",
        "description": "Online design and publishing tool.",
        "employees": "4000"
    },
    {
        "name": "Rivian",
        "legal_name": "Rivian Automotive, Inc.",
        "ticker": "RIVN",
        "category": "Information Technology",
        "subcategory": "Electric Vehicles",
        "careers_url": "https://rivian.com/careers",
        "ats": "Greenhouse",
        "city": "Irvine",
        "state": "CA",
        "country": "US",
        "description": "Designs, develops, manufactures, and sells electric vehicles and accessories.",
        "employees": "14000"
    }
]

os.makedirs('/Volumes/Storage/D Drive /Rep/companies/data/us', exist_ok=True)
with open('/Volumes/Storage/D Drive /Rep/companies/data/us/companies_it_us.json', 'w') as f:
    json.dump(us_it_companies, f, indent=4)
print(f"Generated {len(us_it_companies)} US IT companies.")
